# Environment configuration — DEV
# Used by: databricks.yml targets.dev.variables

catalog: de_assessment_dev
schema: default
environment: dev
num_workers: 1
log_level: DEBUG

cluster:
  spark_version: 15.4.x-scala2.12
  node_type_id: Standard_D4s_v3
  num_workers: 1
  data_security_mode: SINGLE_USER

secrets:
  scope: de-assessment-dev
  databricks_pat_key: databricks-pat
  sp_client_id_key: databricks-sp-client-id
  sp_client_secret_key: databricks-sp-client-secret

storage:
  mount_point: /mnt/de-assessment-dev
  container: de-assessment-dev
  storage_account: stdeassessment

notebook_base_path: /Shared/de-assessment/dev
