terraform {
  required_providers {
    databricks = {
      source  = "databricks/databricks"
      version = "~> 1.0"
    }
  }

  # Remote state — use ARM_ACCESS_KEY or az login (Storage Blob Data Contributor required).
  # In prod: deployer SP needs 'Storage Blob Data Contributor' on this storage account.
  backend "azurerm" {
    resource_group_name  = "de-assessment"
    storage_account_name = "deassessmentd06fabcc"
    container_name       = "tfstate"
    key                  = "infra-databricks/terraform.tfstate"
    use_azuread_auth     = true
  }
}

# Workspace provider — authenticates as deployer SP
# Prerequisite: run infra/account first to register this SP as workspace ADMIN
provider "databricks" {
  host                = var.workspace_url
  azure_client_id     = var.databricks_client_id
  azure_client_secret = var.databricks_client_secret
  azure_tenant_id     = var.azure_tenant_id
}

# ── Storage credential ─────────────────────────────────────────────────────────

resource "databricks_storage_credential" "main" {
  name = "sc-${var.project}"
  azure_managed_identity {
    access_connector_id = var.access_connector_id
    managed_identity_id = var.managed_identity_id
  }
}

# ── External locations — one per medallion layer ───────────────────────────────

resource "databricks_external_location" "layers" {
  for_each        = toset(["raw", "bronze", "silver", "gold"])
  name            = each.key
  url             = "abfss://${each.key}@${var.storage_account_name}.dfs.core.windows.net/"
  credential_name = databricks_storage_credential.main.id
}

# ── Pipeline SP (data source — owned by infra/account) ────────────────────────

data "databricks_service_principal" "pipeline" {
  application_id = var.pipeline_sp_application_id
}

# ── Unity Catalog ──────────────────────────────────────────────────────────────

resource "databricks_catalog" "main" {
  name          = "${var.catalog_name}_${var.environment}"
  owner         = "platform-admins"
  force_destroy = var.environment == "dev"
  storage_root  = "abfss://bronze@${var.storage_account_name}.dfs.core.windows.net/_catalog_managed/"
  depends_on    = [databricks_external_location.layers]
}

resource "databricks_schema" "bronze" {
  catalog_name = databricks_catalog.main.name
  name         = "bronze"
  owner        = "DE-Dev-Team"
}

resource "databricks_schema" "silver" {
  catalog_name = databricks_catalog.main.name
  name         = "silver"
  owner        = "DE-Dev-Team"
}

resource "databricks_schema" "gold" {
  catalog_name = databricks_catalog.main.name
  name         = "gold"
  owner        = "DE-Dev-Team"
}

# ── External location grants — dev only ───────────────────────────────────────
# data.databricks_current_user resolves to the deployer SP when running as SP

data "databricks_current_user" "deployer" {}

resource "databricks_grants" "developer_external_locations" {
  for_each          = var.environment == "dev" ? databricks_external_location.layers : {}
  external_location = each.value.name

  grant {
    principal  = data.databricks_current_user.deployer.user_name
    privileges = ["READ_FILES", "WRITE_FILES", "CREATE_EXTERNAL_TABLE", "CREATE_MANAGED_STORAGE"]
  }

  grant {
    principal  = "DE-Dev-Team"
    privileges = ["READ_FILES", "WRITE_FILES", "CREATE_EXTERNAL_TABLE"]
  }

  grant {
    principal  = data.databricks_service_principal.pipeline.application_id
    privileges = ["READ_FILES", "WRITE_FILES", "CREATE_EXTERNAL_TABLE"]
  }
}


# ── Grants ─────────────────────────────────────────────────────────────────────

resource "databricks_grant" "dev_team_catalog" {
  catalog    = databricks_catalog.main.name
  principal  = "DE-Dev-Team"
  privileges = ["USE_CATALOG", "USE_SCHEMA", "CREATE_SCHEMA", "CREATE_TABLE", "SELECT", "MODIFY", "MANAGE"]
}

resource "databricks_grant" "pipeline_catalog" {
  catalog    = databricks_catalog.main.name
  principal  = data.databricks_service_principal.pipeline.application_id
  privileges = ["USE_CATALOG", "USE_SCHEMA", "CREATE_SCHEMA"]
}

resource "databricks_grant" "pipeline_bronze" {
  schema     = databricks_schema.bronze.id
  principal  = data.databricks_service_principal.pipeline.application_id
  privileges = ["USE_SCHEMA", "SELECT", "MODIFY", "CREATE_TABLE"]
  depends_on = [databricks_grant.pipeline_catalog]
}

resource "databricks_grant" "pipeline_silver" {
  schema     = databricks_schema.silver.id
  principal  = data.databricks_service_principal.pipeline.application_id
  privileges = ["USE_SCHEMA", "SELECT", "MODIFY", "CREATE_TABLE"]
  depends_on = [databricks_grant.pipeline_catalog]
}

# ── Deployer SP — ADF runtime identity (PAT owner) ────────────────────────────
# The ADF linked service uses a PAT generated by the deployer SP.
# It therefore needs the same UC privileges as the pipeline SP.

resource "databricks_grant" "deployer_catalog" {
  catalog    = databricks_catalog.main.name
  principal  = var.databricks_client_id
  privileges = ["USE_CATALOG", "USE_SCHEMA", "CREATE_SCHEMA"]
}

resource "databricks_grant" "deployer_bronze" {
  schema     = databricks_schema.bronze.id
  principal  = var.databricks_client_id
  privileges = ["USE_SCHEMA", "SELECT", "MODIFY", "CREATE_TABLE"]
  depends_on = [databricks_grant.deployer_catalog]
}

resource "databricks_grant" "deployer_silver" {
  schema     = databricks_schema.silver.id
  principal  = var.databricks_client_id
  privileges = ["USE_SCHEMA", "SELECT", "MODIFY", "CREATE_TABLE"]
  depends_on = [databricks_grant.deployer_catalog]
}

resource "databricks_grant" "deployer_gold" {
  schema     = databricks_schema.gold.id
  principal  = var.databricks_client_id
  privileges = ["USE_SCHEMA", "SELECT", "MODIFY", "CREATE_TABLE"]
  depends_on = [databricks_grant.deployer_catalog]
}

resource "databricks_grant" "pipeline_gold" {
  schema     = databricks_schema.gold.id
  principal  = data.databricks_service_principal.pipeline.application_id
  privileges = ["USE_SCHEMA", "SELECT", "MODIFY", "CREATE_TABLE"]
  depends_on = [databricks_grant.pipeline_catalog]
}

# ── BROWSE grant — all account users can discover data ────────────────────────

resource "databricks_grant" "catalog_browse" {
  catalog    = databricks_catalog.main.name
  principal  = "account users"
  privileges = ["BROWSE"]
}

# ── Compliance-Team — read-only access to all layers ─────────────────────────

resource "databricks_grant" "compliance_catalog" {
  catalog    = databricks_catalog.main.name
  principal  = "Compliance-Team"
  privileges = ["USE_CATALOG", "USE_SCHEMA", "SELECT"]
}

# ── DA-Analyst-Team — read-only access to gold layer only ────────────────────

resource "databricks_grant" "analyst_catalog" {
  catalog    = databricks_catalog.main.name
  principal  = "DA-Analyst-Team"
  privileges = ["USE_CATALOG"]
}

resource "databricks_grant" "analyst_gold" {
  schema     = databricks_schema.gold.id
  principal  = "DA-Analyst-Team"
  privileges = ["USE_SCHEMA", "SELECT"]
  depends_on = [databricks_grant.analyst_catalog]
}

# ── Compute policy — enforce UC standard access mode ─────────────────────────
# Prevents users from creating single-node or legacy clusters that bypass UC.

resource "databricks_cluster_policy" "uc_standard" {
  name = "UC Standard Access - ${var.environment}"
  definition = jsonencode({
    "spark_version" : {
      "type" : "unlimited",
      "defaultValue" : "auto:latest-lts"
    },
    "data_security_mode" : {
      "type" : "fixed",
      "value" : "USER_ISOLATION"
    }
  })
}

resource "databricks_permissions" "uc_standard_policy" {
  cluster_policy_id = databricks_cluster_policy.uc_standard.id

  access_control {
    group_name       = "DE-Dev-Team"
    permission_level = "CAN_USE"
  }

  access_control {
    group_name       = "DA-Analyst-Team"
    permission_level = "CAN_USE"
  }

  access_control {
    group_name       = "Compliance-Team"
    permission_level = "CAN_USE"
  }
}
